### ISSUE TITLE
Sun & Moon type icon too high on all templates

### ISSUE THREAD

**Issue by lvandernoll** [lvandernoll/pokecardmaker.net#112]
And pokemon sun and moon the type thing is WAY too high
![Creator _ Pokécardmaker net - Google Chrome 10_1_2022 5_58_13 PM (2)](https://user-images.githubusercontent.com/112284263/193432388-6dbe312e-ddc4-4d9a-901a-3d1a0ee2c830.png)

_Originally posted by @POKEMONG0 in https://github.com/lvandernoll/pokecardmaker.net/discussions/90#discussioncomment-3779822_

**Comment by POKEMONG0** [comment]
FIXXX

**Comment by qwertyuiop265000** [comment]
All Sun/Moon cards, legit or not, have that, so no it isn't.

**Comment by lvandernoll** [comment]
Thanks @qwertyuiop265000, I hadn't thought of checking specific Prism cards. This is indeed a non-issue:
![image](https://user-images.githubusercontent.com/36536517/199972937-4d504d7b-20a2-4cf2-bd12-894ea73b19a3.png)
