### ISSUE TITLE
The "HP" looking very tight

### ISSUE THREAD

**Issue by Prokemon1004** [lvandernoll/pokecardmaker.net#256]
The "HP" word at the up-right side of the card is looking squeezed. Strangely, when it's a "V" card, it's more tight.
### Screenshot
![image](https://user-images.githubusercontent.com/114533511/201493152-b88e749e-f9b1-4671-8434-b881517b3ef7.png)

**Comment by lvandernoll** [comment]
@Prokemon1004 I've made some changes to this. Could you check if it looks better on your end at the moment?

**Comment by Prokemon1004** [comment]
Ok, now it's ok. Thank you very much. I am impressed of your website!

**Comment by ZerglingH** [comment]
When it's a VStar, the HP is now going outside the card :l

**Comment by lvandernoll** [comment]
@ZerglingH this was already the case. It's caused by the templates not being quite right, but I cannot alter them myself because I'm not a designer

**Comment by ZerglingH** [comment]
@lvandernoll ok thank you 👍 : )
