### ISSUE TITLE
Lv X bug

### ISSUE THREAD

**Issue by lvandernoll** [lvandernoll/pokecardmaker.net#258]
### Discussed in https://github.com/lvandernoll/pokecardmaker.net/discussions/257

<div type='discussions-op-text'>

<sup>Originally posted by **SPDragon1** November 12, 2022</sup>
When I download a Lv X with a short name, the Lv X icon in the pokemon's name area overlaps the pokemon's name
![Centiskorch (4)](https://user-images.githubusercontent.com/113554714/201497370-3cb43f69-ea2d-4785-972b-ecf108e57ed7.png)
</div>

**Comment by ZerglingH** [comment]
It's the same thing with other card like V, VStar...

**Comment by qwertyuiop265000** [comment]
Not just short names either.
![Uploading Liy.png…]()
-be me
-create a card with a name so long that the Lv. X logo can barely fit
-have the logo shifted to the left for no reason at all, ruining the card

**Comment by lvandernoll** [comment]
@qwertyuiop265000 Could you upload the image again? When posting an image, wait until the image has uploaded before sending the message please 🙂 

@ZerglingH could you upload an image of what it looks like when it goes wrong, so I can try to replicate and fix it?

**Comment by ZerglingH** [comment]
![image](https://user-images.githubusercontent.com/118122812/201755237-69cd3f07-3b93-48ec-a862-d5acde984114.png)
It's a V card that i made. The V icon is in the ex character. I don't know why the image is not visible

**Comment by lvandernoll** [comment]
@ZerglingH is this a recent image? I believe I've done a fix and this should no longer be wrong

**Comment by lvandernoll** [comment]
Could you try making a new card with the same name and look if it's still an issue?

**Comment by ZerglingH** [comment]
@lvandernoll Yes. I will see if it's possible 👍

**Comment by ZerglingH** [comment]
![Zygarde  e   (1)](https://user-images.githubusercontent.com/118122812/201935889-6fdfd4cd-96c2-4452-9ef8-d3a610cb89dd.png)
@lvandernoll I think it's now working 👍

**Comment by lvandernoll** [comment]
Awesome, thanks for checking!
