### ISSUE TITLE
No Gold Star and Promo Stage 1 and Stage 2

### ISSUE THREAD

**Issue by ZerglingH** [lvandernoll/pokecardmaker.net#267]
There is no Gold Star and Promo rarity for Stage 1 and Stage 2.

2 screenshots :

Basic:                          ![image](https://user-images.githubusercontent.com/118122812/202054615-4d04432f-d4ae-4505-a8af-3aed2a5bcc31.png)

Stage 1 and Stage 2: ![image](https://user-images.githubusercontent.com/118122812/202054411-887ecee0-c0e1-402c-b6cc-e4b6e63b4b6f.png)

(Sorry for editing a lot of times)

**Comment by ZerglingH** [comment]
It's not a bug, it's just something that is missing.

**Comment by lvandernoll** [comment]
Gold Stars have never had stages and were always basic. In the image below you can see that "evolved" Pokémon like Charizard and Umbreon are "Basic" Pokémon.
![image](https://user-images.githubusercontent.com/36536517/202659219-a5585e8a-33f0-43a2-bd79-49a5231354d3.png)

It could still be a cool new feature though, but I will be adding that to the board, not the issue list. Thanks anyways! 🙂
