### ISSUE TITLE
Text does not allign with energy and goes inside the damage.

### ISSUE THREAD

**Issue by VOtolotoo2** [lvandernoll/pokecardmaker.net#283]
When i use a long name the text just goes inside the damage.
![3F5BFF1D-AD82-47FF-8B1D-DF9F7208AFA8](https://user-images.githubusercontent.com/116003169/202916007-a6cce936-2d77-4fbb-b770-a14e40ac8ba6.jpeg)

**Comment by Prokemon1004** [comment]
:L It's an annoying problem...

**Comment by lvandernoll** [comment]
Just like this Spinarak shows, attack names have a minimum distance from the left border of the card, so I do think it's aligned correctly.
I've never seen an attack name that long, if you could show me a real card that has this, I can look into a fix
![image](https://user-images.githubusercontent.com/36536517/203005245-22fad7d8-a764-49a1-8d1a-a9bc4f36cbb8.png)

**Comment by VOtolotoo2** [comment]
I think that is what the people making Pokémon cards try not to make, so I don’t think it exists. Does anyone have a solution?

**Comment by SPDragon1** [comment]
I found a card with an attack so long the text had to be made thinner:
![image](https://user-images.githubusercontent.com/113554714/203890163-e74821b8-2bd5-4d5a-91b4-32d7d79c22e5.png)

**Comment by qwertyuiop265000** [comment]
well, there's your solution, horizontal downscaling.

**Comment by lvandernoll** [comment]
It isn't a simple task for me, though. The maximum width of the text depends on a whole bunch of factors, as it can be different for every single template, with different amounts of energy cost symbols and different damage amounts. I will put this on the backlog as a new feature.
