### ISSUE TITLE
Artwork sticking out of exports

### ISSUE THREAD

**Issue by lvandernoll** [lvandernoll/pokecardmaker.net#287]
**Description**
It seems that the artwork is sticking out of the (top of the) card when using a full-sized image

**Screenshots**
![image](https://user-images.githubusercontent.com/36536517/203013822-5bcc33d0-d3c9-4e31-96c8-18ae76268a2c.png)

**Comment by VOtolotoo2** [comment]
I don’t really understand.

**Comment by EthanPlayz820** [comment]
> 

look at the top corners of the image and you'll see

**Comment by VOtolotoo2** [comment]
…?

**Comment by qwertyuiop265000** [comment]
hardly a problem
