### ISSUE TITLE
Gold Star templates issue

### ISSUE THREAD

**Issue by EthanPlayz820** [lvandernoll/pokecardmaker.net#289]
**Description**
the gold star templates have an issue when you already have the pokedex entry. the entry overlays the rule box.

**Screenshots**
![Screenshot 2022-11-22 9 30 37 PM](https://user-images.githubusercontent.com/113435775/203458957-cf49aab4-5d47-482f-ad72-396ff744fa73.png)

**Comment by lvandernoll** [comment]
Thanks for finding this! I will resolve this soon

**Comment by EthanPlayz820** [comment]
yep! no problem!
