### ISSUE TITLE
Download button working once per site load

### ISSUE THREAD

**Issue by qwertyuiop265000** [lvandernoll/pokecardmaker.net#353]
The Download button works exactly once.
I must refresh to properly download again.

**Comment by lvandernoll** [comment]
I think this is not a bug, but a feature that your browser enforces. Your browser probably blocks any download after the first one, to prevent websites from doing malicious things. See here an example on how to disable this for Chrome: https://www.lifewire.com/download-multiple-files-in-google-chrome-4103618#:~:text=and%20select%20Advanced.-,In%20the%20Privacy%20and%20security%20section%2C%20select%20Content%20settings.,switch%20to%20enable%20the%20setting.

Let me know if this was indeed the issue

**Comment by qwertyuiop265000** [comment]
k thanks
