### ISSUE TITLE
Star variation, Pokedex Stats missing 

### ISSUE THREAD

**Issue by Zaisok** [lvandernoll/pokecardmaker.net#368]
Hello Ivan i found an issue when you choose: 
-Supertype: Pokemon
-Subtype:basic
-Variation: gold star
-Raritiy: NONE (non full art, the full art is working perfectly)

when you choose the non full art gold star variation, the "Pokedex Stats" disappear.

here without the star gold variation
![image](https://user-images.githubusercontent.com/122387418/217264613-c4efa955-f141-4c89-80ec-4d55b8375de2.png)

and here with the star gold variation
![image](https://user-images.githubusercontent.com/122387418/217264694-b6c9cdb5-ef99-4c91-91f5-3c47bb71275c.png)

**Comment by ZerglingH** [comment]
I think that the Pokédex stats bug for the gold star variation is normal. Why? Because I see a dark-yellow line in the bar, like the white line in the ex card. But that's my opinion. Maybe that's a bug... 🤔

**Comment by Prokemon1004** [comment]
Look at this Gold Star Pokémon card, @Zaisok. I think that this is not a problem but it's normal. You can see that on this card, there's no Pokédex stats. Same thing for the V, VMAX, GX, etc. I think that the card designer decided to make resemblance to the official Gold Star cards.
![Latias-gold-star-215x300](https://user-images.githubusercontent.com/114533511/217386086-d97e67ec-e524-4c2b-a2bb-91f8317cfc37.jpg)

**Comment by Zaisok** [comment]
> Look at this Gold Star Pokémon card, @Zaisok. I think that this is not a problem but it's normal. You can see that on this card, there's no Pokédex stats. Same thing for the V, VMAX, GX, etc. I think that the card designer decided to make resemblance to the official Gold Star cards. ![Latias-gold-star-215x300](https://user-images.githubusercontent.com/114533511/217386086-d97e67ec-e524-4c2b-a2bb-91f8317cfc37.jpg)

hello @Prokemon1004 i thinks that no one knows that because the gold stars cards doesnt see play yet, not even in the newest expansion (japan) so we dont know if the idea is to have or not the dex bar. BUT in this page, before the last update, it was possible to fill the dex bar. 
the card you show me was relaese in 2004 aprox. the star template of this page is different from that.

**Comment by ZerglingH** [comment]
> > Look at this Gold Star Pokémon card, @Zaisok. I think that this is not a problem but it's normal. You can see that on this card, there's no Pokédex stats. Same thing for the V, VMAX, GX, etc. I think that the card designer decided to make resemblance to the official Gold Star cards. ![Latias-gold-star-215x300](https://user-images.githubusercontent.com/114533511/217386086-d97e67ec-e524-4c2b-a2bb-91f8317cfc37.jpg)
> 
> hello @Prokemon1004 i thinks that no one knows that because the gold stars cards doesnt see play yet, not even in the newest expansion (japan) so we dont know if the idea is to have or not the dex bar. BUT in this page, before the last update, it was possible to fill the dex bar. the card you show me was relaese in 2004 aprox. the star template of this page is different from that.

@Zaisok But why couldn't I put Pokédex stats before 2023?

**Comment by Zaisok** [comment]
> > > Look at this Gold Star Pokémon card, @Zaisok. I think that this is not a problem but it's normal. You can see that on this card, there's no Pokédex stats. Same thing for the V, VMAX, GX, etc. I think that the card designer decided to make resemblance to the official Gold Star cards. ![Latias-gold-star-215x300](https://user-images.githubusercontent.com/114533511/217386086-d97e67ec-e524-4c2b-a2bb-91f8317cfc37.jpg)
> > 
> > 
> > hello @Prokemon1004 i thinks that no one knows that because the gold stars cards doesnt see play yet, not even in the newest expansion (japan) so we dont know if the idea is to have or not the dex bar. BUT in this page, before the last update, it was possible to fill the dex bar. the card you show me was relaese in 2004 aprox. the star template of this page is different from that.
> 
> @Zaisok But why couldn't I put Pokédex stats on a Gold Star before 2023?

www.pokemon.com, there u can ask that, i think they can answer that.

**Comment by lvandernoll** [comment]
Like @Prokemon1004 said, I removed it on purpose because the original Gold Star cards didn't have it either, and I think it looks better like this. If you disagree, please let me know

**Comment by Zaisok** [comment]
> Like @Prokemon1004 said, I removed it on purpose because the original Gold Star cards didn't have it either, and I think it looks better like this. If you disagree, please let me know

the star card doesn't exist yet, so it's a matter of opinion, i think that its good to have the option, also if i compared the normal cards, the bar it's the same, so it's really probable the new stars could have a dex bar, despite the old one doesn't have one, and not only the stars doesn't have a dex bar all card in that era dosen't have one.

if you don't want to put the dex bar again, can u give me the font and the height, so i can add it with photoshop?

thanks.

**Comment by lvandernoll** [comment]
I agree @Zaisok, I'll add it back and leave it up to the user to decide if they want to use it

**Comment by Zaisok** [comment]
> I agree @Zaisok, I'll add it back and leave it up to the user to decide if they want to use it

thanks!!
