### ISSUE TITLE
Site Text not showing up properly on Microsoft Edge

### ISSUE THREAD

**Issue by EthanPlayz820** [lvandernoll/pokecardmaker.net#454]
**Description**
When I go to the website on my phone or tablet, the site works normally. The words are  white on a light gray background, and it's all the right font size. When I go to the website on my computer (Windows 10 with Microsoft Edge as my main browser) the text is small with the font color the same as the background. There is also no light gray background, and I have a hard time reading it. 

Thank you for your time, 
EthanPlayz820

**Comment by lvandernoll** [comment]
Could you add a screenshot? I use Edge myself and have no issues personally so it's difficult to understand what you're seeing

**Comment by EthanPlayz820** [comment]
I'll have to send it later this week, because my computer is at my relative's house, and my dad has COVID. I'll see if I can go get it, though.

**Comment by JoudKaddour** [comment]
Have you tried on other browsers?

**Comment by EthanPlayz820** [comment]
no, I'll need to install one, but I'll try it. It works on my phone, and I use Google chrome for that.

**Comment by EthanPlayz820** [comment]
I updated my browser and it works fine now 😄
