### ISSUE TITLE
fix text formatting for sv ex cards

### ISSUE THREAD

**Issue by Slap257** [lvandernoll/pokecardmaker.net#482]
**Description**
this has been mentioned before, but there is a problem with long names here. please fix it when you can!

**Screenshots**
in editor:
![Screenshot 2023-06-27 153039](https://github.com/lvandernoll/pokecardmaker.net/assets/137941903/b1c2f4de-170c-4e1c-8dc3-5a97c1b75087)

real card:
![300px-MeowscaradaexPaldeaEvolved15](https://github.com/lvandernoll/pokecardmaker.net/assets/137941903/8510ee11-ea23-490d-b4b1-4bfb32cdc33a)

**Comment by lvandernoll** [comment]
I made a change on this. Could you check whether it looks good now?

**Comment by Slap257** [comment]
Woooo! It works now! Thanks 👏

**Comment by lvandernoll** [comment]
Awesome!
