### ISSUE TITLE
Rotation Icon option "None" ignored upon import

### ISSUE THREAD

**Issue by vandeponcho** [lvandernoll/pokecardmaker.net#486]
Hi Leon, awesome work with the site.

I just noticed that when importing a json file with a card's details, if the rotation icon was originally set to "None", it is reset to the default when importing said file. Thus, it has to be manually changed back to "None".

Also, and although the "Custom" set icon is respected and shown as expected on the card preview, the UI shows the default option as selected (instead of "Custom"). This is however, not a big deal, just a detail. Exporting the result and importing it again still shows the custom icon.

Other than that, exp/imp works like a charm : )

**Comment by lvandernoll** [comment]
Thanks for finding these issues! The fix is deploying now. The first issue will be fixed on imports from now on, and the custom set icon issue is fixed retroactively 👍

**Comment by vandeponcho** [comment]
Works perfectly, thanks!

**Comment by lvandernoll** [comment]
@vandeponcho this is unrelated to this issue, but I noticed all of your cards export without the images on the test gallery. This is an issue I've seen happening a lot but have never figured out why. Could you add me on Discord (shinyangel_) so I can ask you some details?
