### ISSUE TITLE
Grammatical Error on the card generation prompt

### ISSUE THREAD

**Issue by Slap257** [lvandernoll/pokecardmaker.net#543]
**Description**
There is a grammatical error in the pop-up description asking you to keep your cards SFW.
**Screenshots**
![Screenshot 2023-09-02 170205](https://github.com/lvandernoll/pokecardmaker.net/assets/137941903/dfe49de0-12d6-43b9-8bf5-e2e9cb499687)

**Comment by lvandernoll** [comment]
Thanks for letting me know, just fixed this!
