### ISSUE TITLE
Radiant Pokédex entry (found by @masterLAOZ)

### ISSUE THREAD

**Issue by Slap257** [lvandernoll/pokecardmaker.net#552]
**Description**
The text is black, even on Dark templates.

**Screenshots**
![265274691-fcf13386-eb7c-4784-a442-f80b2a13c010](https://github.com/lvandernoll/pokecardmaker.net/assets/137941903/8e8bd556-8a58-41cc-a1b6-a16844ba1696)

**Comment by lvandernoll** [comment]
Fixed
