### ISSUE TITLE
BW/XY Dark Template not showing

### ISSUE THREAD

**Issue by rrcjacket47** [lvandernoll/pokecardmaker.net#587]
**Description**
The BW/XY Dark Template is not showing up for any stages.

**Screenshots**
<img width="987" alt="Screenshot 2023-11-13 at 4 02 43 PM" src="https://github.com/lvandernoll/pokecardmaker.net/assets/63179694/3a062482-dccb-498c-9cc8-d81a01b8c4f6">

**Comment by lvandernoll** [comment]
Should be fixed now
