### ISSUE TITLE
sorry, I'd love to try your website mate sorry my mate dared me to be nasty to someone super sorry

### ISSUE THREAD

**Issue by tommyboii77** [lvandernoll/pokecardmaker.net#77]
i'm gonna stop using this website if people like @tommyboii77 talk like that

_Originally posted by @Bushy45 in https://github.com/lvandernoll/pokecardmaker.net/discussions/49#discussioncomment-3728337_

**Comment by tommyboii77** [comment]
sorry mate id love to try your card maker, my friend dared me to be nasty.. super sorry.. I mean no harm.

**Comment by tommyboii77** [comment]
also sorry @lvandernoll I didn't mean to make this an issue i was meant to put it in disscussion

**Comment by lvandernoll** [comment]
That's fine, I'll close this one
